// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYtiRsfbdaAqsf85EnfxOkE7skZpTL4g',
    appId: '1:418669433715:web:61a5e99d4f0e051b02eb06',
    messagingSenderId: '418669433715',
    projectId: 'nasc-grievance-portal',
    authDomain: 'nasc-grievance-portal.firebaseapp.com',
    storageBucket: 'nasc-grievance-portal.firebasestorage.app',
    measurementId: 'G-KNMF5DMXC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKk7m8lufeOmVgklJLJUd9rzN73fuhAMA',
    appId: '1:418669433715:android:c33e1791a08c9eb302eb06',
    messagingSenderId: '418669433715',
    projectId: 'nasc-grievance-portal',
    storageBucket: 'nasc-grievance-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB47atiIgkWoCoT90lFV5RHXJDpQ8H_YL8',
    appId: '1:418669433715:ios:19a6695d94a30f5d02eb06',
    messagingSenderId: '418669433715',
    projectId: 'nasc-grievance-portal',
    storageBucket: 'nasc-grievance-portal.firebasestorage.app',
    iosBundleId: 'com.example.nascGrievancePortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB47atiIgkWoCoT90lFV5RHXJDpQ8H_YL8',
    appId: '1:418669433715:ios:19a6695d94a30f5d02eb06',
    messagingSenderId: '418669433715',
    projectId: 'nasc-grievance-portal',
    storageBucket: 'nasc-grievance-portal.firebasestorage.app',
    iosBundleId: 'com.example.nascGrievancePortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcYtiRsfbdaAqsf85EnfxOkE7skZpTL4g',
    appId: '1:418669433715:web:104e55b60b050cc202eb06',
    messagingSenderId: '418669433715',
    projectId: 'nasc-grievance-portal',
    authDomain: 'nasc-grievance-portal.firebaseapp.com',
    storageBucket: 'nasc-grievance-portal.firebasestorage.app',
    measurementId: 'G-EKQEQQCTK6',
  );
}
